version: '3.8'

services:
  api:
    build:
      context: ./app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build:
      context: ./streamlit_app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/streamlit_app
    command: streamlit run main.py
    depends_on:
      - api
